services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    image: javier08877/steamlike:4.0
    ports:
      - "3000:80"
    environment:
      BACKEND_URL: http://localhost:8000
    depends_on:
      - web
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
